#!/usr/bin/env bash
# sync-bootstrap.sh
# Merges _shared + per-role docs into ~/.codex/AGENTS.md and verifies ~/.claude/CLAUDE.md symlink.
# Idempotent: safe to re-run on bootstrap and on every standards-repo update.
# Provenance: role-pack distribution pattern adapted from uinaf/agents sync-bootstrap approach.
#
# Usage:
#   bash sync-bootstrap.sh --role=<role> [--company=<company-slug>]
#   bash sync-bootstrap.sh --role=ceo --company=balloon-flow-studio
#
# Roles: ceo | worker | researcher | knowledge-keeper | reviewer
#
# What this script does:
#   1. Validates the role argument.
#   2. Locates the standards repo root (this script's directory).
#   3. Assembles AGENTS.md content: _shared/CONTEXT.md header + role pack index.
#   4. Writes to ~/.codex/AGENTS.md (creates ~/.codex/ if missing).
#   5. Verifies ~/.claude/CLAUDE.md points to ~/CLAUDE.md (symlink check).
#   6. Reports what was written and any warnings.

set -euo pipefail

# ---------------------------------------------------------------------------
# Arguments
# ---------------------------------------------------------------------------
ROLE=""
COMPANY=""

for arg in "$@"; do
  case "$arg" in
    --role=*)  ROLE="${arg#--role=}" ;;
    --company=*) COMPANY="${arg#--company=}" ;;
    *) echo "Unknown argument: $arg" >&2; exit 1 ;;
  esac
done

# ---------------------------------------------------------------------------
# API enum mapping note (v0.2.1)
# The Paperclip API does not accept spec names directly for the 'role' field.
# Use the paperclip_api_role values from config/roles.json when calling
# paperclip_create_agent. Current mappings:
#   spec "worker"           → API role "engineer"
#   spec "knowledge-keeper" → API role "pm"
#   spec "researcher"       → API role "researcher"
#   spec "reviewer"         → API role "qa"
#   spec "ceo"              → API role "ceo"
# self_review_prohibited is NOT a platform-enforced field; it must be
# stated in the Reviewer agent's capabilities/AGENTS.md text.
# ---------------------------------------------------------------------------

VALID_ROLES="ceo worker researcher knowledge-keeper reviewer"
if [[ -z "$ROLE" ]]; then
  echo "ERROR: --role is required. Valid roles: $VALID_ROLES" >&2
  exit 1
fi

ROLE_VALID=0
for r in $VALID_ROLES; do
  [[ "$ROLE" == "$r" ]] && ROLE_VALID=1
done
if [[ "$ROLE_VALID" -eq 0 ]]; then
  echo "ERROR: Unknown role '$ROLE'. Valid roles: $VALID_ROLES" >&2
  exit 1
fi

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SHARED_DIR="$REPO_ROOT/roles/_shared"
ROLE_DIR="$REPO_ROOT/roles/$ROLE"
CODEX_DIR="$HOME/.codex"
AGENTS_MD="$CODEX_DIR/AGENTS.md"
CLAUDE_MD_TARGET="$HOME/CLAUDE.md"
CLAUDE_MD_SYMLINK="$HOME/.claude/CLAUDE.md"

echo "==> sync-bootstrap.sh"
echo "    Role:     $ROLE"
echo "    Company:  ${COMPANY:-<not specified>}"
echo "    Repo:     $REPO_ROOT"
echo "    Output:   $AGENTS_MD"

# ---------------------------------------------------------------------------
# Verify source dirs exist
# ---------------------------------------------------------------------------
if [[ ! -d "$SHARED_DIR" ]]; then
  echo "ERROR: _shared dir not found at $SHARED_DIR" >&2
  exit 1
fi
if [[ ! -d "$ROLE_DIR" ]]; then
  echo "ERROR: Role dir not found at $ROLE_DIR" >&2
  exit 1
fi

# ---------------------------------------------------------------------------
# Create ~/.codex/ if missing
# ---------------------------------------------------------------------------
if [[ ! -d "$CODEX_DIR" ]]; then
  mkdir -p "$CODEX_DIR"
  echo "    Created: $CODEX_DIR"
fi

# ---------------------------------------------------------------------------
# Assemble AGENTS.md
# ---------------------------------------------------------------------------
TMPFILE="$(mktemp)"
trap 'rm -f "$TMPFILE"' EXIT

{
  echo "# AGENTS.md — Role: $ROLE"
  echo "# Auto-generated by sync-bootstrap.sh on $(date -u '+%Y-%m-%d %H:%M UTC')"
  if [[ -n "$COMPANY" ]]; then
    echo "# Company: $COMPANY"
  fi
  echo "# Source: $REPO_ROOT"
  echo ""
  echo "---"
  echo ""

  # Shared vocabulary (always first)
  if [[ -f "$SHARED_DIR/CONTEXT.md" ]]; then
    echo "<!-- BEGIN: roles/_shared/CONTEXT.md -->"
    cat "$SHARED_DIR/CONTEXT.md"
    echo ""
    echo "<!-- END: roles/_shared/CONTEXT.md -->"
    echo ""
  fi

  # Shared contributing rules
  if [[ -f "$SHARED_DIR/CONTRIBUTING.md" ]]; then
    echo "<!-- BEGIN: roles/_shared/CONTRIBUTING.md -->"
    cat "$SHARED_DIR/CONTRIBUTING.md"
    echo ""
    echo "<!-- END: roles/_shared/CONTRIBUTING.md -->"
    echo ""
  fi

  # Shared DoD
  if [[ -f "$SHARED_DIR/DEFINITION-OF-DONE.md" ]]; then
    echo "<!-- BEGIN: roles/_shared/DEFINITION-OF-DONE.md -->"
    cat "$SHARED_DIR/DEFINITION-OF-DONE.md"
    echo ""
    echo "<!-- END: roles/_shared/DEFINITION-OF-DONE.md -->"
    echo ""
  fi

  echo "---"
  echo ""
  echo "# Role pack: $ROLE"
  echo ""

  # All files in role dir, sorted
  for f in "$ROLE_DIR"/*.md; do
    [[ -f "$f" ]] || continue
    fname="$(basename "$f")"
    echo "<!-- BEGIN: roles/$ROLE/$fname -->"
    cat "$f"
    echo ""
    echo "<!-- END: roles/$ROLE/$fname -->"
    echo ""
  done

  # Approval wake protocol (every role needs this)
  if [[ -f "$SCRIPT_DIR/approval-wake-protocol.md" ]]; then
    echo "<!-- BEGIN: standards/approval-wake-protocol.md -->"
    cat "$SCRIPT_DIR/approval-wake-protocol.md"
    echo ""
    echo "<!-- END: standards/approval-wake-protocol.md -->"
    echo ""
  fi

} > "$TMPFILE"

# ---------------------------------------------------------------------------
# Write AGENTS.md (idempotent: only write if content changed)
# ---------------------------------------------------------------------------
if [[ -f "$AGENTS_MD" ]] && diff -q "$TMPFILE" "$AGENTS_MD" > /dev/null 2>&1; then
  echo "    No change: $AGENTS_MD is already up to date."
else
  cp "$TMPFILE" "$AGENTS_MD"
  echo "    Written:  $AGENTS_MD"
fi

# ---------------------------------------------------------------------------
# For Claude-backed roles (ceo, knowledge-keeper), also write to ~/CLAUDE.md
# so that Claude agents (which read CLAUDE.md, not AGENTS.md) receive the
# role pack. Do this BEFORE the symlink check so that ~/CLAUDE.md exists
# when we attempt to create ~/.claude/CLAUDE.md -> ~/CLAUDE.md.
# ---------------------------------------------------------------------------
CLAUDE_ROLES="ceo knowledge-keeper"
IS_CLAUDE_ROLE=0
for cr in $CLAUDE_ROLES; do
  [[ "$ROLE" == "$cr" ]] && IS_CLAUDE_ROLE=1
done

if [[ "$IS_CLAUDE_ROLE" -eq 1 ]]; then
  if [[ -f "$CLAUDE_MD_TARGET" ]] && diff -q "$TMPFILE" "$CLAUDE_MD_TARGET" > /dev/null 2>&1; then
    echo "    No change: $CLAUDE_MD_TARGET is already up to date."
  else
    cp "$TMPFILE" "$CLAUDE_MD_TARGET"
    echo "    Written:  $CLAUDE_MD_TARGET (Claude-backed role: $ROLE)"
  fi
fi

# ---------------------------------------------------------------------------
# Verify ~/.claude/CLAUDE.md symlink
# ---------------------------------------------------------------------------
CLAUDE_DIR="$HOME/.claude"
if [[ ! -d "$CLAUDE_DIR" ]]; then
  mkdir -p "$CLAUDE_DIR"
  echo "    Created:  $CLAUDE_DIR"
fi
if [[ -L "$CLAUDE_MD_SYMLINK" ]]; then
  CURRENT_TARGET="$(readlink "$CLAUDE_MD_SYMLINK")"
  if [[ "$CURRENT_TARGET" == "$CLAUDE_MD_TARGET" ]]; then
    echo "    Verified: $CLAUDE_MD_SYMLINK -> $CLAUDE_MD_TARGET (ok)"
  else
    echo "    WARNING: $CLAUDE_MD_SYMLINK points to $CURRENT_TARGET, expected $CLAUDE_MD_TARGET"
    echo "             Update with: ln -sf $CLAUDE_MD_TARGET $CLAUDE_MD_SYMLINK"
  fi
elif [[ -f "$CLAUDE_MD_SYMLINK" ]]; then
  echo "    WARNING: $CLAUDE_MD_SYMLINK is a regular file, not a symlink."
  echo "             Replace with: ln -sf $CLAUDE_MD_TARGET $CLAUDE_MD_SYMLINK"
else
  if [[ -f "$CLAUDE_MD_TARGET" ]]; then
    ln -sf "$CLAUDE_MD_TARGET" "$CLAUDE_MD_SYMLINK"
    echo "    Created:  $CLAUDE_MD_SYMLINK -> $CLAUDE_MD_TARGET"
  else
    echo "    WARNING: $CLAUDE_MD_TARGET does not exist; symlink not created."
    echo "             Ensure ~/CLAUDE.md exists before running sync-bootstrap."
  fi
fi

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------
echo ""
echo "==> sync-bootstrap complete."
echo "    AGENTS.md role sections: _shared (3 files) + $ROLE ($(ls "$ROLE_DIR"/*.md 2>/dev/null | wc -l | tr -d ' ') files) + approval-wake-protocol"
if [[ -n "$COMPANY" ]]; then
  echo "    Next: copy templates/VISION.md and templates/CEO_BOOTSTRAP.md to company root."
fi
