#!/usr/bin/env bash
# sync-bootstrap.sh
# Merges _shared + per-role docs into a company-scoped AGENTS.md file.
# Idempotent: safe to re-run on bootstrap and on every standards-repo update.
# Provenance: role-pack distribution pattern adapted from uinaf/agents sync-bootstrap approach.
#
# IMPORTANT: This script never touches CC's host CLAUDE.md or ~/.claude/.
# It only writes company-scoped instruction bundles.
#
# Usage:
#   bash sync-bootstrap.sh --role=<role> --company=<company-slug> [--target=<path>] [--dry-run]
#   bash sync-bootstrap.sh --role=ceo --company=balloon-flow-studio
#   bash sync-bootstrap.sh --role=ceo --company=sfx-haptic --dry-run
#   bash sync-bootstrap.sh --role=worker --company=sfx-haptic --target=/custom/path/AGENTS.md
#
# Roles: ceo | worker | researcher | knowledge-keeper | reviewer
#
# What this script does:
#   1. Validates the role argument.
#   2. Locates the standards repo root (this script's directory).
#   3. Assembles AGENTS.md content: _shared/CONTEXT.md header + role pack index.
#   4. Writes to ~/Docs/paperclipcompanies/<company-slug>/AGENTS.md (or --target path).
#   5. Reports what was written and any warnings.

set -euo pipefail

# ---------------------------------------------------------------------------
# Arguments
# ---------------------------------------------------------------------------
ROLE=""
COMPANY=""
TARGET=""
DRY_RUN=0

for arg in "$@"; do
  case "$arg" in
    --role=*)     ROLE="${arg#--role=}" ;;
    --company=*)  COMPANY="${arg#--company=}" ;;
    --target=*)   TARGET="${arg#--target=}" ;;
    --dry-run)    DRY_RUN=1 ;;
    *) echo "Unknown argument: $arg" >&2; exit 1 ;;
  esac
done

# ---------------------------------------------------------------------------
# API enum mapping note (v0.2.1)
# The Paperclip API does not accept spec names directly for the 'role' field.
# Use the paperclip_api_role values from config/roles.json when calling
# paperclip_create_agent. Current mappings:
#   spec "worker"           → API role "engineer"
#   spec "knowledge-keeper" → API role "pm"
#   spec "researcher"       → API role "researcher"
#   spec "reviewer"         → API role "qa"
#   spec "ceo"              → API role "ceo"
# self_review_prohibited is NOT a platform-enforced field; it must be
# stated in the Reviewer agent's capabilities/AGENTS.md text.
# ---------------------------------------------------------------------------

VALID_ROLES="ceo worker researcher knowledge-keeper reviewer"
if [[ -z "$ROLE" ]]; then
  echo "ERROR: --role is required. Valid roles: $VALID_ROLES" >&2
  exit 1
fi

ROLE_VALID=0
for r in $VALID_ROLES; do
  [[ "$ROLE" == "$r" ]] && ROLE_VALID=1
done
if [[ "$ROLE_VALID" -eq 0 ]]; then
  echo "ERROR: Unknown role '$ROLE'. Valid roles: $VALID_ROLES" >&2
  exit 1
fi

if [[ -z "$COMPANY" ]]; then
  echo "ERROR: --company is required." >&2
  exit 1
fi

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SHARED_DIR="$REPO_ROOT/roles/_shared"
ROLE_DIR="$REPO_ROOT/roles/$ROLE"

# Default target: ~/Docs/paperclipcompanies/<company-slug>/AGENTS.md
if [[ -z "$TARGET" ]]; then
  TARGET="$HOME/Docs/paperclipcompanies/$COMPANY/AGENTS.md"
fi

TARGET_DIR="$(dirname "$TARGET")"

echo "==> sync-bootstrap.sh"
echo "    Role:     $ROLE"
echo "    Company:  $COMPANY"
echo "    Repo:     $REPO_ROOT"
echo "    Output:   $TARGET"
if [[ "$DRY_RUN" -eq 1 ]]; then
  echo "    Mode:     DRY RUN (nothing will be written)"
fi

# ---------------------------------------------------------------------------
# Verify source dirs exist
# ---------------------------------------------------------------------------
if [[ ! -d "$SHARED_DIR" ]]; then
  echo "ERROR: _shared dir not found at $SHARED_DIR" >&2
  exit 1
fi
if [[ ! -d "$ROLE_DIR" ]]; then
  echo "ERROR: Role dir not found at $ROLE_DIR" >&2
  exit 1
fi

# ---------------------------------------------------------------------------
# Assemble AGENTS.md into a temp file
# ---------------------------------------------------------------------------
TMPFILE="$(mktemp)"
trap 'rm -f "$TMPFILE"' EXIT

{
  echo "# AGENTS.md — Role: $ROLE"
  echo "# Auto-generated by sync-bootstrap.sh on $(date -u '+%Y-%m-%d %H:%M UTC')"
  echo "# Company: $COMPANY"
  echo "# Source: $REPO_ROOT"
  echo "# NOTE: This file is company-scoped. CC's host CLAUDE.md is never touched by this script."
  echo ""
  echo "---"
  echo ""

  # Shared vocabulary (always first)
  if [[ -f "$SHARED_DIR/CONTEXT.md" ]]; then
    echo "<!-- BEGIN: roles/_shared/CONTEXT.md -->"
    cat "$SHARED_DIR/CONTEXT.md"
    echo ""
    echo "<!-- END: roles/_shared/CONTEXT.md -->"
    echo ""
  fi

  # Shared contributing rules
  if [[ -f "$SHARED_DIR/CONTRIBUTING.md" ]]; then
    echo "<!-- BEGIN: roles/_shared/CONTRIBUTING.md -->"
    cat "$SHARED_DIR/CONTRIBUTING.md"
    echo ""
    echo "<!-- END: roles/_shared/CONTRIBUTING.md -->"
    echo ""
  fi

  # Shared DoD
  if [[ -f "$SHARED_DIR/DEFINITION-OF-DONE.md" ]]; then
    echo "<!-- BEGIN: roles/_shared/DEFINITION-OF-DONE.md -->"
    cat "$SHARED_DIR/DEFINITION-OF-DONE.md"
    echo ""
    echo "<!-- END: roles/_shared/DEFINITION-OF-DONE.md -->"
    echo ""
  fi

  echo "---"
  echo ""
  echo "# Role pack: $ROLE"
  echo ""

  # All files in role dir, sorted
  for f in "$ROLE_DIR"/*.md; do
    [[ -f "$f" ]] || continue
    fname="$(basename "$f")"
    echo "<!-- BEGIN: roles/$ROLE/$fname -->"
    cat "$f"
    echo ""
    echo "<!-- END: roles/$ROLE/$fname -->"
    echo ""
  done

  # Approval wake protocol (every role needs this)
  if [[ -f "$SCRIPT_DIR/approval-wake-protocol.md" ]]; then
    echo "<!-- BEGIN: standards/approval-wake-protocol.md -->"
    cat "$SCRIPT_DIR/approval-wake-protocol.md"
    echo ""
    echo "<!-- END: standards/approval-wake-protocol.md -->"
    echo ""
  fi

  # CC-to-CEO communication protocol (every role needs awareness)
  if [[ -f "$SCRIPT_DIR/cc-paperclip-communication-protocol.md" ]]; then
    echo "<!-- BEGIN: standards/cc-paperclip-communication-protocol.md -->"
    cat "$SCRIPT_DIR/cc-paperclip-communication-protocol.md"
    echo ""
    echo "<!-- END: standards/cc-paperclip-communication-protocol.md -->"
    echo ""
  fi

} > "$TMPFILE"

# ---------------------------------------------------------------------------
# Dry-run: print content and exit
# ---------------------------------------------------------------------------
if [[ "$DRY_RUN" -eq 1 ]]; then
  echo ""
  echo "==> DRY RUN — content that would be written to $TARGET:"
  echo "------------------------------------------------------------"
  cat "$TMPFILE"
  echo "------------------------------------------------------------"
  echo "==> DRY RUN complete. Nothing was written."
  exit 0
fi

# ---------------------------------------------------------------------------
# Create target directory if missing
# ---------------------------------------------------------------------------
if [[ ! -d "$TARGET_DIR" ]]; then
  mkdir -p "$TARGET_DIR"
  echo "    Created: $TARGET_DIR"
fi

# ---------------------------------------------------------------------------
# Write AGENTS.md (idempotent: only write if content changed)
# ---------------------------------------------------------------------------
if [[ -f "$TARGET" ]] && diff -q "$TMPFILE" "$TARGET" > /dev/null 2>&1; then
  echo "    No change: $TARGET is already up to date."
else
  cp "$TMPFILE" "$TARGET"
  echo "    Written:  $TARGET"
fi

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------
echo ""
echo "==> sync-bootstrap complete."
echo "    AGENTS.md role sections: _shared (3 files) + $ROLE ($(ls "$ROLE_DIR"/*.md 2>/dev/null | wc -l | tr -d ' ') files) + approval-wake-protocol + cc-paperclip-communication-protocol"
echo "    Next: ensure Paperclip agent instructionsFilePath points to $TARGET"
